### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ExTBH**

### CODE REVIEW

**Comment by ExTBH** [comment]
- [ ] Migrate Logging to new way

**Comment by krooom68** [comment]
https://github.com/ExTBH/JodelEmproved/commit/77f36e0fcf6b4ca4bb3471d05d129c58f8c1f604

**Review by krooom68 — COMMENTED** [review]
F

**Comment by ExTBH** [comment]
> F

Wth is wrong with you

**Pull request merged**
